using System.Collections.Generic;

namespace BlazorClient.Helpers;

public class CountryInfo
{
    public string Code { get; set; } = string.Empty;
    public string Name { get; set; } = string.Empty;

    public override string ToString() => $"{Name} ({Code})";
}

public static class CountryHelper
{
    public static List<CountryInfo> Countries { get; } = new()
    {
        new() { Code = "AF", Name = "Afeganistão" },
        new() { Code = "ZA", Name = "África do Sul" },
        new() { Code = "AL", Name = "Albânia" },
        new() { Code = "DE", Name = "Alemanha" },
        new() { Code = "AD", Name = "Andorra" },
        new() { Code = "AO", Name = "Angola" },
        new() { Code = "AI", Name = "Anguilla" },
        new() { Code = "AQ", Name = "Antártida" },
        new() { Code = "AG", Name = "Antígua e Barbuda" },
        new() { Code = "SA", Name = "Arábia Saudita" },
        new() { Code = "DZ", Name = "Argélia" },
        new() { Code = "AR", Name = "Argentina" },
        new() { Code = "AM", Name = "Armênia" },
        new() { Code = "AW", Name = "Aruba" },
        new() { Code = "AU", Name = "Austrália" },
        new() { Code = "AT", Name = "Áustria" },
        new() { Code = "AZ", Name = "Azerbaijão" },
        new() { Code = "BS", Name = "Bahamas" },
        new() { Code = "BH", Name = "Bahrein" },
        new() { Code = "BD", Name = "Bangladesh" },
        new() { Code = "BB", Name = "Barbados" },
        new() { Code = "BE", Name = "Bélgica" },
        new() { Code = "BZ", Name = "Belize" },
        new() { Code = "BJ", Name = "Benin" },
        new() { Code = "BM", Name = "Bermudas" },
        new() { Code = "BY", Name = "Bielorrússia" },
        new() { Code = "BO", Name = "Bolívia" },
        new() { Code = "BA", Name = "Bósnia e Herzegovina" },
        new() { Code = "BW", Name = "Botsuana" },
        new() { Code = "BR", Name = "Brasil" },
        new() { Code = "BN", Name = "Brunei" },
        new() { Code = "BG", Name = "Bulgária" },
        new() { Code = "BF", Name = "Burkina Faso" },
        new() { Code = "BI", Name = "Burundi" },
        new() { Code = "BT", Name = "Butão" },
        new() { Code = "CV", Name = "Cabo Verde" },
        new() { Code = "KH", Name = "Camboja" },
        new() { Code = "CM", Name = "Camarões" },
        new() { Code = "CA", Name = "Canadá" },
        new() { Code = "QA", Name = "Catar" },
        new() { Code = "KZ", Name = "Cazaquistão" },
        new() { Code = "TD", Name = "Chade" },
        new() { Code = "CL", Name = "Chile" },
        new() { Code = "CN", Name = "China" },
        new() { Code = "CY", Name = "Chipre" },
        new() { Code = "CO", Name = "Colômbia" },
        new() { Code = "KM", Name = "Comores" },
        new() { Code = "CG", Name = "Congo-Brazzaville" },
        new() { Code = "CD", Name = "Congo-Kinshasa" },
        new() { Code = "KP", Name = "Coreia do Norte" },
        new() { Code = "KR", Name = "Coreia do Sul" },
        new() { Code = "CI", Name = "Costa do Marfim" },
        new() { Code = "CR", Name = "Costa Rica" },
        new() { Code = "HR", Name = "Croácia" },
        new() { Code = "CU", Name = "Cuba" },
        new() { Code = "CW", Name = "Curaçao" },
        new() { Code = "DK", Name = "Dinamarca" },
        new() { Code = "DJ", Name = "Djibuti" },
        new() { Code = "DM", Name = "Dominica" },
        new() { Code = "EG", Name = "Egito" },
        new() { Code = "SV", Name = "El Salvador" },
        new() { Code = "AE", Name = "Emirados Árabes Unidos" },
        new() { Code = "EC", Name = "Equador" },
        new() { Code = "ER", Name = "Eritreia" },
        new() { Code = "SK", Name = "Eslováquia" },
        new() { Code = "SI", Name = "Eslovênia" },
        new() { Code = "ES", Name = "Espanha" },
        new() { Code = "US", Name = "Estados Unidos" },
        new() { Code = "EE", Name = "Estônia" },
        new() { Code = "ET", Name = "Etiópia" },
        new() { Code = "FJ", Name = "Fiji" },
        new() { Code = "PH", Name = "Filipinas" },
        new() { Code = "FI", Name = "Finlândia" },
        new() { Code = "FR", Name = "França" },
        new() { Code = "GA", Name = "Gabão" },
        new() { Code = "GM", Name = "Gâmbia" },
        new() { Code = "GH", Name = "Gana" },
        new() { Code = "GE", Name = "Geórgia" },
        new() { Code = "GI", Name = "Gibraltar" },
        new() { Code = "GR", Name = "Grécia" },
        new() { Code = "GD", Name = "Granada" },
        new() { Code = "GL", Name = "Groenlândia" },
        new() { Code = "GP", Name = "Guadalupe" },
        new() { Code = "GU", Name = "Guam" },
        new() { Code = "GT", Name = "Guatemala" },
        new() { Code = "GG", Name = "Guernsey" },
        new() { Code = "GY", Name = "Guiana" },
        new() { Code = "GF", Name = "Guiana Francesa" },
        new() { Code = "GN", Name = "Guiné" },
        new() { Code = "GQ", Name = "Guiné Equatorial" },
        new() { Code = "GW", Name = "Guiné-Bissau" },
        new() { Code = "HT", Name = "Haiti" },
        new() { Code = "HN", Name = "Honduras" },
        new() { Code = "HK", Name = "Hong Kong" },
        new() { Code = "HU", Name = "Hungria" },
        new() { Code = "YE", Name = "Iêmen" },
        new() { Code = "IM", Name = "Ilha de Man" },
        new() { Code = "CX", Name = "Ilha Christmas" },
        new() { Code = "NF", Name = "Ilha Norfolk" },
        new() { Code = "AX", Name = "Ilhas Aland" },
        new() { Code = "KY", Name = "Ilhas Cayman" },
        new() { Code = "CK", Name = "Ilhas Cook" },
        new() { Code = "FO", Name = "Ilhas Faroé" },
        new() { Code = "GS", Name = "Ilhas Geórgia do Sul e Sandwich do Sul" },
        new() { Code = "HM", Name = "Ilhas Heard e McDonald" },
        new() { Code = "FK", Name = "Ilhas Malvinas" },
        new() { Code = "MP", Name = "Ilhas Marianas do Norte" },
        new() { Code = "MH", Name = "Ilhas Marshall" },
        new() { Code = "UM", Name = "Ilhas Menores Distantes dos EUA" },
        new() { Code = "PN", Name = "Ilhas Pitcairn" },
        new() { Code = "SB", Name = "Ilhas Salomão" },
        new() { Code = "TC", Name = "Ilhas Turcas e Caicos" },
        new() { Code = "VG", Name = "Ilhas Virgens Britânicas" },
        new() { Code = "VI", Name = "Ilhas Virgens Americanas" },
        new() { Code = "IN", Name = "Índia" },
        new() { Code = "ID", Name = "Indonésia" },
        new() { Code = "IR", Name = "Irã" },
        new() { Code = "IQ", Name = "Iraque" },
        new() { Code = "IE", Name = "Irlanda" },
        new() { Code = "IS", Name = "Islândia" },
        new() { Code = "IL", Name = "Israel" },
        new() { Code = "IT", Name = "Itália" },
        new() { Code = "JM", Name = "Jamaica" },
        new() { Code = "JP", Name = "Japão" },
        new() { Code = "JE", Name = "Jersey" },
        new() { Code = "JO", Name = "Jordânia" },
        new() { Code = "KW", Name = "Kuwait" },
        new() { Code = "LA", Name = "Laos" },
        new() { Code = "LS", Name = "Lesoto" },
        new() { Code = "LV", Name = "Letônia" },
        new() { Code = "LB", Name = "Líbano" },
        new() { Code = "LR", Name = "Libéria" },
        new() { Code = "LY", Name = "Líbia" },
        new() { Code = "LI", Name = "Liechtenstein" },
        new() { Code = "LT", Name = "Lituânia" },
        new() { Code = "LU", Name = "Luxemburgo" },
        new() { Code = "MO", Name = "Macau" },
        new() { Code = "MK", Name = "Macedônia do Norte" },
        new() { Code = "MG", Name = "Madagascar" },
        new() { Code = "MY", Name = "Malásia" },
        new() { Code = "MW", Name = "Malaui" },
        new() { Code = "MV", Name = "Maldivas" },
        new() { Code = "ML", Name = "Mali" },
        new() { Code = "MT", Name = "Malta" },
        new() { Code = "MA", Name = "Marrocos" },
        new() { Code = "MQ", Name = "Martinica" },
        new() { Code = "MU", Name = "Maurício" },
        new() { Code = "MR", Name = "Mauritânia" },
        new() { Code = "YT", Name = "Mayotte" },
        new() { Code = "MX", Name = "México" },
        new() { Code = "FM", Name = "Micronésia" },
        new() { Code = "MZ", Name = "Moçambique" },
        new() { Code = "MD", Name = "Moldávia" },
        new() { Code = "MC", Name = "Mônaco" },
        new() { Code = "MN", Name = "Mongólia" },
        new() { Code = "ME", Name = "Montenegro" },
        new() { Code = "MS", Name = "Montserrat" },
        new() { Code = "MM", Name = "Myanmar" },
        new() { Code = "NA", Name = "Namíbia" },
        new() { Code = "NR", Name = "Nauru" },
        new() { Code = "NP", Name = "Nepal" },
        new() { Code = "NI", Name = "Nicarágua" },
        new() { Code = "NE", Name = "Níger" },
        new() { Code = "NG", Name = "Nigéria" },
        new() { Code = "NU", Name = "Niue" },
        new() { Code = "NO", Name = "Noruega" },
        new() { Code = "NC", Name = "Nova Caledônia" },
        new() { Code = "NZ", Name = "Nova Zelândia" },
        new() { Code = "OM", Name = "Omã" },
        new() { Code = "NL", Name = "Países Baixos" },
        new() { Code = "PW", Name = "Palau" },
        new() { Code = "PS", Name = "Palestina" },
        new() { Code = "PA", Name = "Panamá" },
        new() { Code = "PG", Name = "Papua-Nova Guiné" },
        new() { Code = "PK", Name = "Paquistão" },
        new() { Code = "PY", Name = "Paraguai" },
        new() { Code = "PE", Name = "Peru" },
        new() { Code = "PF", Name = "Polinésia Francesa" },
        new() { Code = "PL", Name = "Polônia" },
        new() { Code = "PR", Name = "Porto Rico" },
        new() { Code = "PT", Name = "Portugal" },
        new() { Code = "KE", Name = "Quênia" },
        new() { Code = "KG", Name = "Quirguistão" },
        new() { Code = "KI", Name = "Quiribati" },
        new() { Code = "GB", Name = "Reino Unido" },
        new() { Code = "CF", Name = "República Centro-Africana" },
        new() { Code = "DO", Name = "República Dominicana" },
        new() { Code = "CZ", Name = "República Tcheca" },
        new() { Code = "RE", Name = "Reunião" },
        new() { Code = "RO", Name = "Romênia" },
        new() { Code = "RW", Name = "Ruanda" },
        new() { Code = "RU", Name = "Rússia" },
        new() { Code = "EH", Name = "Saara Ocidental" },
        new() { Code = "WS", Name = "Samoa" },
        new() { Code = "AS", Name = "Samoa Americana" },
        new() { Code = "SM", Name = "San Marino" },
        new() { Code = "SH", Name = "Santa Helena" },
        new() { Code = "LC", Name = "Santa Lúcia" },
        new() { Code = "BL", Name = "São Bartolomeu" },
        new() { Code = "KN", Name = "São Cristóvão e Névis" },
        new() { Code = "MF", Name = "São Martinho" },
        new() { Code = "PM", Name = "São Pierre e Miquelon" },
        new() { Code = "VC", Name = "São Vicente e Granadinas" },
        new() { Code = "ST", Name = "São Tomé e Príncipe" },
        new() { Code = "SN", Name = "Senegal" },
        new() { Code = "SL", Name = "Serra Leoa" },
        new() { Code = "RS", Name = "Sérvia" },
        new() { Code = "SC", Name = "Seychelles" },
        new() { Code = "SG", Name = "Singapura" },
        new() { Code = "SX", Name = "Sint Maarten" },
        new() { Code = "SY", Name = "Síria" },
        new() { Code = "SO", Name = "Somália" },
        new() { Code = "LK", Name = "Sri Lanka" },
        new() { Code = "SZ", Name = "Suazilândia" },
        new() { Code = "SD", Name = "Sudão" },
        new() { Code = "SS", Name = "Sudão do Sul" },
        new() { Code = "SE", Name = "Suécia" },
        new() { Code = "CH", Name = "Suíça" },
        new() { Code = "SR", Name = "Suriname" },
        new() { Code = "SJ", Name = "Svalbard e Jan Mayen" },
        new() { Code = "TH", Name = "Tailândia" },
        new() { Code = "TW", Name = "Taiwan" },
        new() { Code = "TJ", Name = "Tajiquistão" },
        new() { Code = "TZ", Name = "Tanzânia" },
        new() { Code = "TF", Name = "Territórios Franceses do Sul" },
        new() { Code = "IO", Name = "Território Britânico do Oceano Índico" },
        new() { Code = "TL", Name = "Timor-Leste" },
        new() { Code = "TG", Name = "Togo" },
        new() { Code = "TK", Name = "Tokelau" },
        new() { Code = "TO", Name = "Tonga" },
        new() { Code = "TT", Name = "Trinidad e Tobago" },
        new() { Code = "TN", Name = "Tunísia" },
        new() { Code = "TM", Name = "Turcomenistão" },
        new() { Code = "TR", Name = "Turquia" },
        new() { Code = "TV", Name = "Tuvalu" },
        new() { Code = "UA", Name = "Ucrânia" },
        new() { Code = "UG", Name = "Uganda" },
        new() { Code = "UY", Name = "Uruguai" },
        new() { Code = "UZ", Name = "Uzbequistão" },
        new() { Code = "VU", Name = "Vanuatu" },
        new() { Code = "VA", Name = "Vaticano" },
        new() { Code = "VE", Name = "Venezuela" },
        new() { Code = "VN", Name = "Vietnã" },
        new() { Code = "WF", Name = "Wallis e Futuna" },
        new() { Code = "ZM", Name = "Zâmbia" },
        new() { Code = "ZW", Name = "Zimbábue" }
    };

    public static string GetCountryName(string code)
    {
        var country = Countries.Find(c => string.Equals(c.Code, code, System.StringComparison.OrdinalIgnoreCase));
        return country?.Name ?? code;
    }

    public static string RemoveDiacritics(string text)
    {
        if (string.IsNullOrWhiteSpace(text))
            return text;

        var normalizedString = text.Normalize(System.Text.NormalizationForm.FormD);
        var stringBuilder = new System.Text.StringBuilder(normalizedString.Length);

        foreach (var c in normalizedString)
        {
            var unicodeCategory = System.Globalization.CharUnicodeInfo.GetUnicodeCategory(c);
            if (unicodeCategory != System.Globalization.UnicodeCategory.NonSpacingMark)
            {
                stringBuilder.Append(c);
            }
        }

        return stringBuilder.ToString().Normalize(System.Text.NormalizationForm.FormC);
    }
}
