using System;

namespace BlazorClient.Helpers
{
    public static class ImageHelper
    {
        private static bool IsStorageUrl(string url)
        {
            if (string.IsNullOrEmpty(url)) return false;
            
            return url.Contains("r2.cloudflarestorage.com") ||
                   url.Contains("minio") ||
                   url.Contains("localhost:59100") ||
                   url.Contains("127.0.0.1:59100");
        }

        /// <summary>
        /// Generates a srcset string based on the object-storage image naming convention (filename_WxH.ext).
        /// </summary>
        public static string GetSrcset(string? url)
        {
            if (string.IsNullOrEmpty(url) || url.Contains("default-placeholder") || !IsStorageUrl(url))
            {
                return string.Empty;
            }

            // Standard sizes generated by our recommended config
            var sizes = new[] { 200, 400, 800 };
            var srcsetItems = new System.Collections.Generic.List<string>();

            foreach (var size in sizes)
            {
                var resizedUrl = GetResizedUrl(url, size, size);
                srcsetItems.Add($"{resizedUrl} {size}w");
            }

            return string.Join(", ", srcsetItems);
        }

        /// <summary>
        /// Generates a URL for a specific image size based on the suffix convention.
        /// </summary>
        public static string GetResizedUrl(string url, int width, int height)
        {
            if (string.IsNullOrEmpty(url) || !IsStorageUrl(url))
            {
                return url;
            }

            try
            {
                // Object-storage URLs may contain a query string after the object path.
                // The filename is between %2F (or last /) and the next . (extension)
                
                int questionMarkIndex = url.IndexOf('?');
                string baseUrl = questionMarkIndex > 0 ? url.Substring(0, questionMarkIndex) : url;
                string queryParams = questionMarkIndex > 0 ? url.Substring(questionMarkIndex) : "";

                int lastDotIndex = baseUrl.LastIndexOf('.');
                if (lastDotIndex == -1) return url;

                string pathWithoutExt = baseUrl.Substring(0, lastDotIndex);
                string extension = baseUrl.Substring(lastDotIndex);

                // Note: The Resize Images extension usually appends _WxH before the extension
                return $"{pathWithoutExt}_{width}x{height}{extension}{queryParams}";
            }
            catch
            {
                return url;
            }
        }
    }
}
